language: python
python:
  - "3.6"
cache:
  pip: true
  directories:
    - _build/html
install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: test
      script: make doctest

    - stage: test
      script: make coverage

    - stage: build
      script: sphinx-build -q -b html . _build/html -d _build/doctrees
      skip_cleanup: true

    - stage: deploy
      script: mkdir artifact && tar czvf artifact/lfzyx.org.tar.gz -C _build/html .
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: _build/html
        fqdn: lfzyx.org
        target-branch: master
        on:
          branch: master


